name: Called-Workflow-A

on:
  workflow_call:
    inputs:
      username:
        required: true
        type: string
	secrets:
      DB_USER:
        required: true

jobs:
  example_job:
    runs-on: ubuntu-latest
    steps:
      - name: Run a hello world script
        run: echo Hello, ${{ inputs.username }}
      - name: Check if we get the secret from caller workflow
        run: echo ${{ secrets.DB_USER }} | sed 's/./& /g'
